### ISSUE TITLE
how to call WyvernExchangeContract to mumbai

### ISSUE THREAD

**Issue by Paris-LIN** [wyvernprotocol/wyvern-v3#54]
mumbai node: https://rpc-mumbai.maticvigil.com/v1/mykey

self.web3ContractInstance.validateOrderParameters_.call(addrs_0[0], addrs_0[1], addrs_0[5], '0x00000000', '0x', 1, 0, 1000000000000, 0)

call result:

(node:4173) UnhandledPromiseRejectionWarning: Error: execution reverted
    at Object.InvalidResponse (/usr/nft/openlake-js/node_modules/wyvern-js/node_modules/_web3@0.20.7@web3/lib/web3/errors.js:38:16)
    at /usr/nft/openlake-js/node_modules/wyvern-js/node_modules/_web3@0.20.7@web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/usr/nft/openlake-js/node_modules/_web3@0.20.7@web3/lib/web3/httpprovider.js:129:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/nft/openlake-js/node_modules/_xhr2-cookies@1.1.0@xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/usr/nft/openlake-js/node_modules/_xhr2-cookies@1.1.0@xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/usr/nft/openlake-js/node_modules/_xhr2-cookies@1.1.0@xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/usr/nft/openlake-js/node_modules/_xhr2-cookies@1.1.0@xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1198:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

anyone know how to solve this problem?

**Comment by junaidShaikh** [comment]
did you deploy the contract cluster on the Polygon-Mumbai network?
